# Generated by Django 5.0.8 on 2025-12-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("service_fee", models.PositiveIntegerField()),
                ("mpesa_phone", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DISBURSED", "Disbursed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_fee_paid", models.BooleanField(default=False)),
                (
                    "paystack_reference",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "last_event",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="loans_loan_user_id_d0fb34_idx"
                    ),
                    models.Index(
                        fields=["paystack_reference"],
                        name="loans_loan_paystac_49f755_idx",
                    ),
                ],
            },
        ),
    ]
