# Generated by Django 5.0.8 on 2025-12-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.contrib.postgres.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('service_fee', models.PositiveIntegerField()),
                ('mpesa_phone', models.CharField(max_length=12)),
                (
                    'status',
                    models.CharField(
                        max_length=16,
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('DISBURSED', 'Disbursed'),
                        ],
                        default='PENDING',
                    ),
                ),
                ('service_fee_paid', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(max_length=64, blank=True, null=True, unique=True)),
                ('last_event', models.CharField(max_length=255, default='', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='loans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'status'], name='loans_user_status_idx'),
                    models.Index(fields=['paystack_reference'], name='loans_paystack_reference_idx'),
                ],
            },
        ),
    ]
